build: off

before_test:
- appveyor\\before_test.cmd

clone_folder: "c:\\stack"
environment:
  global:
    STACK_ROOT: "c:\\sr"

test_script:
# The ugly echo "" hack is to avoid complaints about 0 being an invalid file
# descriptor
- echo "" | stack --no-terminal build

cache:
- c:\\sr
- C:\Users\appveyor\AppData\Local\Programs\stack